Repository RelationalAI-oss/Salsa.jl, pull requests merged in 2020-03, with the labels that each got.

#1 Wrap Salsa Exceptions thrown from Salsa to allow pretty-printing a salsa trace
  src/Salsa.jl
  test/Salsa.jl
Labels: enhancement, error handling

#2 Fix bug in derived functions over multiple components.
  src/Salsa.jl
  test/Salsa.jl
Labels: bug

#3 Disable wrapping exceptions in `SalsaDerivedException()` for now.
  src/Salsa.jl
  test/Salsa.jl
Labels: error handling

#4 Add minimal README; share w/ Salsa module docs
  README.md
  src/Salsa.jl
Labels: documentation

#5 Performance Optimization: De-duplicating Derived Function Traces
  src/Salsa.jl
Labels: enhancement, performance

#6 Add Spreadsheet App Example
  examples/SpreadsheetApp/Manifest.toml
  examples/SpreadsheetApp/Project.toml
  examples/SpreadsheetApp/README.md
  examples/SpreadsheetApp/src/Spreadsheet.jl
  examples/SpreadsheetApp/src/SpreadsheetApp.jl
  examples/SpreadsheetApp/src/UI.jl
Labels: examples
