Repository RelationalAI-oss/Salsa.jl, pull requests merged in 2020-07, with the labels that each got.

#23 Upstream from RelationalAI: re-enable pretty-printed stacks; performance tuning; add simple microbenchmark
  Project.toml
  bench/README.md
  bench/benchmark.jl
  src/Debug.jl
  src/Salsa.jl
  src/default_storage.jl
  test/Salsa.jl
  test/runtests.jl
Labels: upstream

#24 Salsa Example: Linear Regression + Incremental Maintenance
  examples/ML-LR-IVM/linear-regression-incremental.jl
  examples/ML-LR-IVM/linear-regression.jl
Labels: examples

#26 Fix bug in Salsa stack trace printing: off-by-one
  src/Salsa.jl
Labels: bug, error handling

#27 Upstream from RelationalAI: Salsa performance improvements: Remove allocations
  src/Salsa.jl
  src/default_storage.jl
  test/Salsa.jl
Labels: performance, upstream

#28 Fix SalsaWrappedException when ENV["SALSA_STATIC_DEBUG"] is disabled
  src/Salsa.jl
Labels: bug

#29 Fix up Salsa.Inspect.build_graph after DefaultStorage perf changes
  Project.toml
  src/inspect.jl
Labels: bug

#31 Fix where clauses for Derived Functions
  Project.toml
  src/Salsa.jl
  test/Salsa.jl
Labels: macros

#32 Add support for default values for Salsa derived functions
  src/Salsa.jl
  test/Salsa.jl
Labels: macros
